name: Compile the accounts microservice
description: Builds and publishes the container with the accounts service

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: build
          ref: main

      - name: Checking out personalf-services
        working-directory: build
        run: |
          git clone ${{ var.PERSONALF_SERVICES_REPO_URL }}

      - name: Setting variables for container build
        run: | 
          echo "CURRENT_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
          echo "IMAGE_NAME= eosorio/personalf-services-accounts" >> $GITHUB_ENV

      - name: Build the image and tagging as latest
        working-directory: build
        run: |
          ls -l
          docker build -t ${{ env.IMAGE_NAME }}:${{ env.CURRENT_DATE }} -f personalf-services-accounts/Containerfile .
          docker tag ${{ env.IMAGE_NAME }}:${{ env.CURRENT_DATE }} ${{ vars.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.CURRENT_DATE }}
          docker tag ${{ env.IMAGE_NAME }}:${{ env.CURRENT_DATE }} ${{ vars.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Push images to registry
        run: |
          docker push ${{ vars.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.CURRENT_DATE }}
          docker push ${{ vars.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
